version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: binance-api-node
    versions:
    - 0.10.25
    - 0.10.26
    - 0.10.28
    - 0.10.29
    - 0.10.30
    - 0.10.32
    - 0.10.33
    - 0.10.34
    - 0.10.35
    - 0.10.36
    - 0.10.37
    - 0.10.38
    - 0.10.40
  - dependency-name: dateformat
    versions:
    - 4.5.0
  - dependency-name: node-telegram-bot-api
    versions:
    - 0.51.0
